### PR TITLE
Fix page title for dashboard

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
This PR fix missings title for all dashboard pages.

### CODE REVIEW

**Review by wafflecoffee — CHANGES_REQUESTED** [review]
"Notifications" is spelled incorrectly; and shouldn't the "mods" in "My mods" be capitalised for consistency?

**Comment by Mysterious-Dev** [comment]
@wafflecoffee You mean "My Mods ?"

**Comment by wafflecoffee** [comment]
That's what I personally think it should be corrected to, yes

**Comment by Mysterious-Dev** [comment]
Like that ?

image
image

**Review by wafflecoffee — APPROVED** [review]

**Review by falseresync — CHANGES_REQUESTED** [review]
Uppercase "M" is a typo in `Followed Mods`, not in `My mods`, i.e. all "M"s should be lowercase, since that's what all other pages and titles use

**Comment by Redblueflame** [comment]
@falseresync https://knossos-fix-title-fmswbvsadgsu.herokuapp.com/

**Pull request merged**
