### PR TITLE
Mod Manager Integration

### PR DESCRIPTION
**Pull request by trash-pandy**
A partial implementation for issue #380.
Currently adds a button next to any downloads that launches a protocol handler intended to be received by an application on the user's computer that is configured to handle it. The protocol handler currently takes the form `modrinth:/add-item/<version-id>`, where `<version-id>` is the version of the item selected to be downloaded. The button can be enabled by adding the `manager-integration` parameter to the page URL, which is intended to be used by the application referenced above.

### CODE REVIEW

**Review by Geometrically — CHANGES_REQUESTED** [review]
Nice job on the implementation! I am going to leave this on requested changes for now. I think before merging the spec should be documented @ https://docs.modrinth.com. I'll talk with the rest of the team on what the spec would look like + any additional features it may support

**Comment by MulverineX** [comment]
Maybe have the button always be there but unless the cookie has been set have it open to the modrinth launcher page?

**Comment by trash-panda-mc** [comment]
> Maybe have the button always be there but unless the cookie has been set have it open to the modrinth official launcher page?

Perhaps in future, when Theseus is in a more useable state, but that day is yet to come.

**Comment by trash-panda-mc** [comment]
There were some major merge conflicts that I found were much easier to resolve by resetting my fork to the latest upstream commit and re-adding what I had written.

**Comment by triphora** [comment]
Hey @trash-pandy! Would it be possible for you to recreate this PR on master? We're still interested in getting this merged, but the rewrite is on hold the foreseeable future, so it would be better to add this to the current Nuxt site.

**Comment by Minenash** [comment]
If this gets merged, probably would be good to let launchers know this is planned so they can add it before the button appears (I see the polymc one above, but it's still open, and prism is the new poly so)

Also maybe the link should be a bit different, as add-item sounds weird for stuff like modpacks

**Comment by triphora** [comment]
Closing in favor of #783

**Pull request closed without merging**
