### PR TITLE
Add LiteLoader, Rift, 'Other' mod loaders (Fixes #148)

### LINKED ISSUE #148: Add LiteLoader, Rift, etc. mod loaders
**Is your feature request related to a problem? Please describe.**
I've seen a couple people complain about LiteLoader and Rift not being loader options for mods on Modrinth.

**Describe the solution you'd like**
For them to be added as loader options instead of just having Fabric and Forge.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by wafflecoffee**
remake of #154

### CODE REVIEW

**Review by rubybb — COMMENTED** [review]
This needs to be implemented in the backend first iirc.
As the list of loaders is returned from https://api.modrinth.com/api/v1/tag/loader.
Not really optimal for multiple games currently; but I suppose that's a problem for later.

**Comment by wafflecoffee** [comment]
I don't see anything in the backend even mentioning Fabric or Forge explicitly except in a comment

**Comment by rubybb** [comment]
> I don't see anything in the backend even mentioning Fabric or Forge explicitly except in a comment

They're located in a database. It's not hard coded I'm pretty sure.

**Comment by wafflecoffee** [comment]
ah. Well, can't make a PR for that. Geo & folk know what they're doing

**Review by falseresync — CHANGES_REQUESTED** [review]
Please, provide screenshots for visual changes. Also, this has to wait before API has the functionality.

PS did you commit the icons? I don't see them

**Comment by wafflecoffee** [comment]
> PS did you commit the icons? I don't see them

I was unsure how to get those icons so I did not (that's why the build fails). I created a symlink on my local system for those to the misc.svg just so that it'd build

**Comment by falseresync** [comment]
Loader icons are hand-drawn. You may take an attempt (and for liteloader you can use feather icon)

**Comment by wafflecoffee** [comment]
This can be handled by someone else - with everything that's happened recently, someone with more authority than myself should be making decisions on which loaders and all are to be added. As I stated in the previous PR - mess from beginning to end lol

**Pull request closed without merging**
