### PR TITLE
General UI Improvement (again)

### LINKED ISSUE #208: Make download buttons stand out and download icon be reserved for actual downloading
I think the download buttons for mods should be a blue color to help make it stand out against all the options on the website. There's so many buttons and stuff but users are going to be mainly looking for the download button. And by having the button blue like links are, it signals that the button is a link too.
Untitled

In this mock-up picture, the blue helps to know what is clickable as in the bottom picture, the downloads count icon tricked me into thinking that's where I download the mod. This is because the button uses the exact same icon is used for downloading in the top picture.

Having an icon be used for two different purposed is generally bad design as now the users has to think about where they are to know if they can click it instead of recognizing the icon as being a download button right away. 

So my thought is, perhaps change the download icon in the bottom picture to a different icon or make it also be a second button to download the mod. If it is a download link too, then it should be colored blue like the regular download button to show that either of these buttons can be used to download the mod. 

I think this small change will greatly help navigability of the site for people unfamiliar with it as the color really helps draw their attention the button they will be looking for 99% of the time.

### LINKED ISSUE #239: Download buttons don't act like buttons
**Describe the bug**
Despite being the same color as a bunch of other buttons (which is about to change, but even still), but it doesn't act like one. Unlike other buttons, it doesn't darken when hovered.

**To Reproduce**
1. Go to a mod page
2. Hover over download button
3. See no visual indication besides cursor

**Expected behavior**
The button to darken

### LINKED ISSUE #251: "Confirm leaving" prompt upon leaving new version, new mod etc pages
**Is your feature request related to a problem? Please describe.**
If you put in a lot of information to a new version, new mod, edit version, or edit mod page, and then accidentally do something to leave the page (e.g. accidentally press the back button on a mouse), your changes are not saved upon going back.

**Describe the solution you'd like**
A prompt asking you to confirm leaving the page if you do an action where the data input might be removed (e.g. back button, closing the tab, etc.)

**Describe alternatives you've considered**
It could also somehow save that data for a short amount of time in local storage (idk if that's possible/feasible though)

### PR DESCRIPTION
**Pull request by impossiblereality**
A better version of #229.

Also makes fetch on the search page async so that [this](https://discord.com/channels/734077874708938864/734082619352023081/847510062566080572) doesn't happen.

Fixes #239
Implements/closes #251
Fixes #208

### CODE REVIEW

**Review by wafflecoffee — CHANGES_REQUESTED** [review]
Could the page leave confirmation also be implemented on the mod creation page? (`pages/mod/create`)

**Comment by WickedTree** [comment]
> Could the page leave confirmation also be implemented on the mod creation page? (`pages/mod/create`)

I'm on it

**Comment by wafflecoffee** [comment]
Hmm.. image (and yes I actually made sure my adblockers were off this time)

**Comment by WickedTree** [comment]
uh oh...

**Review by wafflecoffee — APPROVED** [review]
No issues found in my testing!

**Review by Mysterious-Dev — APPROVED** [review]

**Comment by Geometrically** [comment]
@Redblueflame Could you do a deployment of this?

**Comment by venashial** [comment]
@Geometrically Here's one https://knossos-venashial-pv8iu4o56-venashial.vercel.app/

**Review by Geometrically — APPROVED** [review]

**Pull request merged**
