### PR TITLE
Sort mod versions by publish date

### PR DESCRIPTION
**Pull request by FlashyReese**
It's not actually comparing to sort since the API already returns time in order.

### CODE REVIEW

**Comment by falseresync** [comment]
Is this tested? May you also implement a switch to reverse order?
Code notice: better do the operation once where it fetches the list

**Comment by FlashyReese** [comment]
> Is this tested? May you also implement a switch to reverse order?
> Code notice: better do the operation once where it fetches the list

Yes I have tested this, I'm not good at frontend but I can try implementing a switch.

**Comment by falseresync** [comment]
Just slam it somewhere, design is relatively easy to fix afterwards

**Comment by falseresync** [comment]
Already fixed

**Pull request closed without merging**
