### PR TITLE
added support for the kbd tag in markdown editor

### PR DESCRIPTION
**Pull request by jadelily18**
* added kbd tag to whitelist in `plugins/xss.js`
* added styles for the kbd selector in `assets/styles/global.scss`

### CODE REVIEW

**Review by wafflecoffee — APPROVED** [review]

**Comment by Andre601** [comment]
To give some input, would it be a difficult task to implement characters for specific kbd cases?

Like when someone has `<kbd>cmd</kbd>` that it would display as <kbd>⌘ Cmd</kbd>?
Would IMO make the kbd a little bit better outside of simply adding minor styling to it...

Tho that's just an idea and not really a needed thing.

**Comment by wafflecoffee** [comment]
Well, if someone wanted to have one that says ⌘, they would use ⌘. The reason this PR was opened is because we don't support it at all at the moment.

**Comment by Andre601** [comment]
When I understand this PR right is this only adding the `<kbd>` HTML syntax to be usable, not any markdown-like formatting, right?

**Review by isXander — APPROVED** [review]
Yes please!

**Comment by Minenash** [comment]
I didn't even know this tag existed. I've been using inline code blocks, this could be great!

**Pull request merged**
