### PR TITLE
Improve badges and work on a more unified color scheme for random colors

### PR DESCRIPTION
**Pull request by Prospector**
Examples of the new badges and color scheme in action:

image
image

### CODE REVIEW

**Review by triphora — APPROVED** [review]

**Comment by Andre601** [comment]
Quickly providing my own feedback on this...
How would this be in regards to colour blind people? Those suffering a red-green blindness may have a difficult time seeing a difference between the release and the (I assume) alpha releases. Perhaps the changelog should in a future update have some more unique symbols to indicate the type of release?

Of course, I'm not one having a color blindness, so I could be wrong here on if that is having a negative impact at all... But it should be considered for the future.

**Comment by Jamalam360** [comment]
Oh hello there. I'm quite serverely red-green colourblind. I'll preface this by saying the condition is very variable from person to person, even with the same type (red-green etc.), but from the screenshot those colours are definitely defined enough for me to see the difference quite clearly.

**Review by Geometrically — APPROVED** [review]

**Comment by Andre601** [comment]
> Oh hello there. I'm quite serverely red-green colourblind. I'll preface this by saying the condition is very variable from person to person, even with the same type (red-green etc.), but from the screenshot those colours are definitely defined enough for me to see the difference quite clearly.

Thanks for the clarification.
I quickly tested around using a a11y add-on to see and from the testing, people with Achromatomaly would have the strongest impact (See screenshot)

But as you said does it all depend on the person, since not everyone has the same level of impact on it.
Just think that a symbol of sorts could still help in the future... Tho then we would need to make it clear what the icon means. :/
Maybe a title on hover saying the type (If that is doable)?

Screenshot as mentioned:
grafik

**Comment by Prospector** [comment]
At least for me, even in that screenshot the brightness of the color is distinct enough to distinguish each release channel for me. I do think adding an icon is a good idea though and maybe something we would consider in the future. In fact, this PR replaces pure color circles with icons in other places with the badges

**Pull request merged**
