### PR TITLE
Homepage styling improvements

### PR DESCRIPTION
**Pull request by venashial**
### Video before
image

### Video after
image

------

### Code before
image

### Code after 
image

### CODE REVIEW

**Comment by ImpossibleReality** [comment]
I swear I've changed that code snippet to look good at least 100 times...

**Comment by venashial** [comment]
Deploy: https://knossos-venashial-obbshxf25-venashial.vercel.app/

**Review by ImpossibleReality — CHANGES_REQUESTED** [review]
Maybe change `black` to `#171719` for consistency? (huh apparently github shows colors now, thats cool XD)

**Comment by venashial** [comment]
Deploy: https://knossos-venashial-cyp6svui0-venashial.vercel.app/

**Review by ImpossibleReality — APPROVED** [review]
Looks good :D

**Review by Mysterious-Dev — APPROVED** [review]
LGTM

**Comment by ImpossibleReality** [comment]
Maybe crop the video so that the scroll bar isn't visible?
(looks kinda weird in both dark and light mode)
image

**Comment by wafflecoffee** [comment]
Personally, I'd more prefer that the video be ridded of entirely in favour of an animation of a search bar and results or something like that. Having a static video in the first place where nothing is legible is kind of clunky, anyway.

**Review by Geometrically — APPROVED** [review]

**Pull request merged**
