### PR TITLE
Add autocomplete attribute for 2fa input

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
All is in the title ^^.

This is a QOL improvement for password manager users .

### CODE REVIEW

**Comment by Mysterious-Dev** [comment]
Well, I added autocomplete property because some password manager can store 2fa code (and adding this property let password manager suggest a field completion)

**Comment by Mysterious-Dev** [comment]
@Geometrically Any news for this PR ? Are we waiting for the rework?

**Comment by Mysterious-Dev** [comment]
Merge conflicts resolved ^^.

**Review by xtexChooser — APPROVED** [review]

**Comment by xtexChooser** [comment]
LGTM, adding these attributes also make password managers able to fill these fields automatically

**Comment by Mysterious-Dev** [comment]
I removed inputmode property for backup code.

**Comment by Mysterious-Dev** [comment]
Any news or feedback for this PR ?

**Review by Prospector — APPROVED** [review]

**Pull request merged**
