### PR TITLE
Make responsive

### PR DESCRIPTION
**Pull request by stairman06**
Self explanatory.

### CODE REVIEW

**Review by falseresync — APPROVED** [review]
Code looks good, although I would greatly advice to mobile-first approach (min-width, instead of max-width) for maintainability reasons. Using desktop-first is good for sketching, while mobile-first is good for sustaining. I would also advice to move the page label (E.g. “Mods”) to the top bar, next to the logo, when the sidebar menu is collapsed. You may just duplicate the label and show the appropriate one on demand.

**Comment by stairman06** [comment]
Changed to be mobile first, and merged upstream so no more merge conflicts. I didn't add the label to the navbar as I'm unfamiliar with Nuxt and not sure of the proper way to do it.

**Comment by Geometrically** [comment]
Pushing my local changes in an hour, there might be some more conflicts - once those are fixed, this should be good for merge.

**Comment by stairman06** [comment]
Merge conflicts have been resolved and the version selector works well.

**Review by Geometrically — APPROVED** [review]

**Pull request merged**
