### PR TITLE
Add query to embed of search pages

### PR DESCRIPTION
**Pull request by Kxffie**

### CODE REVIEW

**Comment by Prospector** [comment]
What does this actually look like? Wouldn't it basically just look like a bunch of nonsense in the title?

**Comment by Kxffie** [comment]
If you look at the embed for https://modrinth-searchterm-n512.vercel.app/mods?q=fred, you will see it says its genre and "fred"

Mods | fred

**Comment by Prospector** [comment]
ah ok, just the search term I see. I thought this was applying like the query parameters string to it and was like what lol

**Review by triphora — CHANGES_REQUESTED** [review]
Lint is failing

**Comment by Kxffie** [comment]
how do I fix this?

**Comment by triphora** [comment]
pnpm run fix

**Review by triphora — APPROVED** [review]

**Pull request merged**
