### PR TITLE
Fix formatting of money values

### LINKED ISSUE #736: Incorrect formatting of balance in Dashboard
### Environment

Website

### Describe the bug

The balance in the dashboard isn't properly formatted

### Steps To Reproduce

1. Have $0.10 in your dashboard balance

### Expected behavior

The balance would show as $0.10

### PR DESCRIPTION
**Pull request by smcmo**
Fixes #736 and #782

This has some minor code duplication but it's the best idea I could think of, all things considered. Let me know if something could use improvement.

### CODE REVIEW

**Comment by smcmo** [comment]
Figured I should visually indicate what this means.

**Old display** (what's currently on production, note the $0.1)
image
image

**With changes:**
image
image

**Comment by Jamalam360** [comment]
I wonder if the `NumberFormat` API would work? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

**Review by triphora — COMMENTED** [review]
Will be unneeded if #738 gets merged first, so I'll mark that PR as closing this one

**Comment by smcmo** [comment]
> I wonder if the `NumberFormat` API would work? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

This would make sense considering #738. I'll leave this PR as is and revisit if it becomes necessary.

**Review by Geometrically — APPROVED** [review]
PR looks good and is fine to merge (translation is somewhat far)

**Pull request merged**
