### PR TITLE
Fix notifications not being able to be dismissed

### PR DESCRIPTION
**Pull request by venashial**
In line 42,
```html
<button @click="performAction(notification, null)">Dismiss</button>
```
`null` is passed into the function, not `undefined`. This makes the `undefined` IF statement pass and knossos tries sending a broken request and fails. Changing the IF statement to `if (index !== null)` fixes the issue.

### CODE REVIEW

**Comment by venashial** [comment]
Deploy: https://knossos-venashial-b3pgtbf3q-venashial.vercel.app/

**Review by triphora — COMMENTED** [review]
#178 goes back to being unfixed with this, unless that's intentional.

**Comment by venashial** [comment]
I don't think it was ever fixed, but I can fix it now

**Comment by venashial** [comment]
Deploy: https://knossos-venashial-hi4br5pii-venashial.vercel.app/

**Comment by venashial** [comment]
#178 is now truly fixed

**Review by Mysterious-Dev — APPROVED** [review]
LGTM

**Review by Redblueflame — APPROVED** [review]
LGTM

**Pull request merged**
