### PR TITLE
Theme switch cooldown

### PR DESCRIPTION
**Pull request by NerjalNosk**
Prevent theme spam-switch (preventing epilepsy risks)

### CODE REVIEW

**Review by Mysterious-Dev — APPROVED** [review]
Love it

**Review by Mysterious-Dev — APPROVED** [review]
LGTM

**Review by triphora — APPROVED** [review]

**Comment by triphora** [comment]
whoops I pushed the wrong branch. Will re-create as a separate PR

**Comment by triphora** [comment]
Merged as 776c16cd49dd994e357d979a7824b77927dfc662

**Pull request closed without merging**
