### PR TITLE
Add translation keys for collections 

### LINKED ISSUE #1554: Incorrect 'project' word ending at Collections page
### Describe the bug

Incorrect 'project' word ending ('projects' instead of 'project') at Collections page if selected collection has only one project

On this screen you can see that 'Test' collection has 1 'projects' instead of 'project'
Снимок экрана (741)

### Steps to reproduce

1. Go to Collections page
2. Create a collection
3. Add only one project
4. Go to Collections page again
5. You'll see that created collection has '1 projects' instead of '1 project'

### Expected behavior

Collection with only one project must have '1 project' instead of '1 projects' parameter

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
All is in the title ^^.

Related to #1454  
Close #1554

### CODE REVIEW

**Comment by Mysterious-Dev** [comment]
Ready for review (@brawaru the stage is yours ^^)

**Comment by Mysterious-Dev** [comment]
I convert this PR as a draft. I must wait for the merge of #1434

**Review by Prospector — APPROVED** [review]

**Comment by brawaru** [comment]
@Mysterious-Dev, can you please merge https://github.com/Mysterious-Dev/knossos/pull/8?

**Comment by Mysterious-Dev** [comment]
> @Mysterious-Dev, can you please merge https://github.com/Mysterious-Dev/knossos/pull/8? 

It's merged 👍

**Comment by Prospector** [comment]
got some conflicts with common-messages and the collection page due to other PRs being merged

**Comment by Mysterious-Dev** [comment]
> got some conflicts with common-messages and the collection page due to other PRs being merged

Resolved ^^.

**Pull request merged**
