### PR TITLE
Complete Rewrite: SvelteKit, Typescript, i18n, BEM styling

### PR DESCRIPTION
**Pull request by venashial**
### Major changes

- [SvelteKit](https://kit.svelte.dev/)
	- [Svelte](https://github.com/sveltejs/svelte#what-is-svelte)
		- Better performance (No virtual DOM)
		- Easier for people to contribute that only have knowledge of HTML & CSS
	- [Vite](https://vitejs.dev/guide/why.html)
		- quick dev server start using native ESM
- [Typescript](https://www.typescriptlang.org/)
	- API response types from open-api spec
- [Internationalization](https://svelte-intl-precompile.com/) modrinth/translations#11 
- [BEM styling](http://getbem.com/introduction/)
- [PostCSS](https://github.com/postcss/postcss#postcss-)
	- modern CSS syntax
	- extensibility
- [Iconify](https://iconify.design/)
	- icons downloaded and bundled automatically

### Minor changes

- theme switcher supports "system theme"
- new 404 error page
- `/discord` redirects to discord server

<details>
  <summary><b>Show screenshots</b></summary>

| image |
| --- |
| image |

</details>

### CODE REVIEW

**Comment by RedstoneWizard08** [comment]
Hello! I fixed a bug where the authentication code parameter from GitHub stays in the URL query after returning to the API callback.

Here's the code:
```svelte
<script lang="ts">
import { page } from '$app/stores';
import { goto } from '$app/navigation';
import { onMount } from 'svelte';

const checkCode = () => {
  if ($page.url.searchParams.get('code')) {
    $page.url.searchParams.delete('code');
    const params: string[] = [];
    $page.url.searchParams.forEach((v, k) => params.push(`${k}=${v}`));
    const url = $page.url.pathname + (params.length > 0 ? '?' : '') + params.join('&');
    goto(url);
  }
};

onMount(() => checkCode());
</script>
```
I am also working on this for other features in a separate repo, too.

**Comment by NatoBoram** [comment]
Hey, that's amazing. SvelteKit & TypeScript are very fun to work with.

**Comment by RedstoneWizard08** [comment]
> Hey, that's amazing. SvelteKit & TypeScript are very fun to work with.

^^ this

**Comment by triphora** [comment]
Closing this since the rewrite is indefinitely on hold. We're going to go forward using Vue/Nuxt for the time being and will reevaluate at a later date whether we want to switch to Svelte. Likely won't be for quite a long time while we focus on roadmap items.

**Pull request closed without merging**
