### PR TITLE
Markdown styling fixes

### PR DESCRIPTION
**Pull request by venashial**
### Current styling:
Screenshot 2021-06-21 at 11-42-06 Mud Mod - Modrinth

-----

### Improved styling:
Screenshot 2021-06-21 at 11-42-22 Mud Mod - Modrinth

----

### Darkmode version of new styling:
Screenshot 2021-06-21 at 11-47-24 Mud Mod - Modrinth

----

Code blocks with long lines still cause styling problems. I did make them scrollable though.

### CODE REVIEW

**Comment by venashial** [comment]
Deploy: https://knossos-venashial-d7yng8uv6-venashial.vercel.app

**Review by Redblueflame — APPROVED** [review]
Looks good to me, only CSS changes.
Will merge it once the workflow finishes :)

**Review by wafflecoffee — APPROVED** [review]
It would have been nice if this included a fix for wonky code blocks (i.e. like the one found [here](https://knossos-venashial-d7yng8uv6-venashial.vercel.app/mod/styledplayerlist)), but LGTM

**Review by Mysterious-Dev — APPROVED** [review]
LGTM.

**Comment by venashial** [comment]
> It would have been nice if this included a fix for wonky code blocks (i.e. like the one found [here](https://knossos-venashial-d7yng8uv6-venashial.vercel.app/mod/styledplayerlist)), but LGTM
@wafflecoffee 

I tried, but I cannot figure out a way to do it nicely without setting breakpoints and `px` values.

**Pull request merged**
