### PR TITLE
[simple]: add title to leave project button

### LINKED ISSUE #1478: Explain why Leave project button is disabled
### Is your suggested enhancement related to a problem? Please describe.

In the `members` section of a project's settings, there is a button labeled "Leave project" under the "Manage members" section. This button can sometimes be grayed out, (I assume if you are the project owner). However, there is no information displayed as to why you cannot leave the project.

### Describe the solution you'd like

Add some kind of indicator (like a tooltip) to that button that explains why it is grayed out.

### Describe alternatives you've considered

_No response_

### Additional context

image

### PR DESCRIPTION
**Pull request by AdamRaichu**
Closes #1478

(Original pull deleted due to merge confilcts)

### CODE REVIEW

**Review by Geometrically — CHANGES_REQUESTED** [review]
This should use the v-tooltip API

**Comment by Prospector** [comment]
> This should use the v-tooltip API

v-tooltip annoyingly does not work on disabled buttons

**Comment by AdamRaichu** [comment]
> This should use the v-tooltip API

I don't know what that is, I'm not a react dev. Also, @Prospector says that won't work here.

@Prospector does that mean you think it should be merged as-is, or a different change should be made?

**Comment by Prospector** [comment]
Will merge since it's at least a minor improvement

**Pull request merged**
