### PR TITLE
add notifications dropdown

### LINKED ISSUE #718: Notification Button Dropdown
### Is your feature request related to a problem? Please describe.

When checking Notifications you don't necessarily want to open a whole new Page.

### Describe the solution you'd like

Make the Notifiations Button open a Dropdown with the first x Notifications and some Buttons like
-"Clear All" (Delete all notifications)
-"Show All" (Load the full Notifications Page)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Arbee4ever**
This should work now ._:
resolves #718

### CODE REVIEW

**Comment by Arbee4ever** [comment]
resolves #718

**Comment by HyperSoop** [comment]
Why do you need a clunky see all button when the whole notif page is opened on click anyway

**Comment by jadelily18** [comment]
> Why do you need a clunky see all button when the whole notif page is opened on click anyway

That's the point of the PR

**Comment by falseresync** [comment]
This could be good if you:
- retain the notifications as a button
- fix padding: see all button is too close to the list
- update the PR to match the master branch

**Comment by falseresync** [comment]
Also: 
- fix the individual close button, it's way too small
- hide the scrollbar when unnecessary
- account for the scrollbar width, so that it doesn't overlap the notification

**Pull request closed without merging**
