### PR TITLE
Clean rewrite

### PR DESCRIPTION
**Pull request by falseresync**
### Code quality
- [x] Introduce Vuex
- [ ] Remove unnecessary dependencies (so far: Axios, Nuxt Auth)
- [ ] Reuse much more styling
- [ ] Improve performance by caching request data in Vuex
- [ ] Introduce Composition API
- [ ] Separate concerns: not a single API call should be outside the direct user or common API
- [ ] Use NuxtChild and multiple layouts instead of XPage components
- [ ] Move some features like categories list to frontend (self-) API

### Design
- [ ] Move away from box shadows
- [ ] Introduce consistent guidelines
- [ ] Convert everything to [BEM](https://en.bem.info/methodology/quick-start/)
- [ ] Modify and use [SimpleMDE](https://simplemde.com/)
- [ ] Condense spacing
- [ ] Make it more official and less all over the place
- [ ] Redo the landing page

### Accessibility
- [ ] Add accessibility I guess?

### Responsiveness
- [x] Header
- [ ] Footer
- [ ] Landing page
- [ ] Mods search
- [ ] Mod creation
- [ ] Mod page
- [ ] Mod settings
- [ ] Versions list
- [ ] Version details
- [ ] Version edit
- [ ] User page
- [ ] User notifications
- [ ] User settings

### New pages
- [ ] Mod changelog

**This list is not exhaustive and will be updated regularly**

### CODE REVIEW

**Comment by Boundarybreaker** [comment]
> Add accessibility I guess?

this seems, really abstract for something that should be pretty concrete - if you don't know what accessibility stuff needs to be added, I can write an up an accessibility audio for you.

~~the tone also feels dismissive and like it's low-priority even though accessibility is really crucial~~

**Comment by falseresync** [comment]
@Boundarybreaker this isn't really dismissive, I know quite a lot about accessibility on the web, and current Modrinth design even has several accessibility decisions. The tone is the way it is because accessibility has been considered, but hasn't been prioritized or made consistent. The category is empty since I have yet to figure out which accessibility features and design choices need to be made

**Comment by Boundarybreaker** [comment]
Good to know it's cared about. I'm still happy to do an audit of current design features and what could be improved, though.

**Comment by falseresync** [comment]
Thanks, that would be very helpful

**Comment by Mysterious-Dev** [comment]
This PR is dead no ?

**Comment by Redblueflame** [comment]
Not really. It's still being worked on as far as I know, but the progress is not shared.

**Comment by falseresync** [comment]
Closing in favor of refactoring. It is almost empty anyway

**Pull request closed without merging**
