### PR TITLE
Restore transparency in project icons

### PR DESCRIPTION
**Pull request by Gaming32**

### CODE REVIEW

**Comment by Rafii2198** [comment]
Instead of removing shadow completely, I would replace it with drop-shadow, so it would look like this:
obraz

*Note that these values are not original values and I just made them to see how it looks and of course is just my opinion*

**Comment by Prospector** [comment]
This change was intentional

**Comment by Gaming32** [comment]
> Instead of removing shadow completely, I would replace it with drop-shadow, so it would look like this: obraz
> 
> _Note that these values are not original values and I just made them to see how it looks and of course is just my opinion_

That looks good.

**Comment by Gaming32** [comment]
> This change was intentional

Doesn't make it necessarily the best change. I got quite a few people on Discord saying they prefer the changes in this PR.

**Comment by intergrav** [comment]
I agree. I feel like the icon background isn't that necessary

**Comment by Gaming32** [comment]
Discussion moved to https://discord.com/channels/734077874708938864/1045786101673111553 (Modrinth Discord)

**Pull request closed without merging**
