### PR TITLE
Add 'Switch to Dark/Light Mode' to header & footer (Fixes #174)

### LINKED ISSUE #174: Dark mode requires you to be logged in
**Describe the bug**
Title

**To Reproduce**
1. Log out
2. Try and go to dark mode

**Expected behavior**
There should be a way (maybe in footer?) to switch to dark mode even when not signed in

### PR DESCRIPTION
**Pull request by wafflecoffee**

### CODE REVIEW

**Review by Mysterious-Dev — APPROVED** [review]

**Review by falseresync — CHANGES_REQUESTED** [review]
Could you also add it as icon-only button next to `Sign in` button?

**Comment by Redblueflame** [comment]
https://knossos-darkmodefooter-lc5ivge.herokuapp.com/

**Comment by wafflecoffee** [comment]
> Could you also add it as icon-only button next to `Sign in` button?

I've got it working well on mobile!
mobile header
But it's still broken on desktop
desktop header
and I'm not sure how to fix it :confused:

**Comment by falseresync** [comment]
@wafflecoffee wrap it inside another DIV together with the second button

**Comment by wafflecoffee** [comment]
Tried doing that, broke the login button alignment on mobile.

**Comment by wafflecoffee** [comment]
https://cdn.discordapp.com/attachments/745980892735864953/835256687803367464/modrinth-2021-04-23_16.50.59.webm for demonstration in case Heroku does a dummy again

**Review by falseresync — APPROVED** [review]
I don't see any criminal CSS, hence good to go

**Pull request merged**
