### PR TITLE
Rework user dropdown, redo mobile navigation, improve 'home' page

### PR DESCRIPTION
**Pull request by Prospector**
Forgot to push this the other day when I did it.

### CODE REVIEW

**Comment by Prospector** [comment]
Ah, right. I had some ideas for alternative navigation on mobile, I'll try to get around to implementing them later today perhaps.

**Review by wafflecoffee — COMMENTED** [review]
One problem I've found: after clicking a button on the "More" context menu to go to another page, it doesn't switch back to saying "More"; it still says "Less". Otherwise, LGTM

**Comment by Prospector** [comment]
Fixing that is being surprisingly difficult... hmm

**Comment by Prospector** [comment]
I'm not sure how to reasonably fix this. If anyone has any ideas, let me know, otherwise I might have to just make the button static or remove the text entirely or something.

**Comment by Geometrically** [comment]
> I'm not sure how to reasonably fix this. If anyone has any ideas, let me know, otherwise I might have to just make the button static or remove the text entirely or something.

Use vue route watchers to reset the state, you can see the search for an example or the version page

**Comment by Prospector** [comment]
Fixed the "More" text

**Review by Mysterious-Dev — APPROVED** [review]
LGTM

**Review by wafflecoffee — APPROVED** [review]

**Review by Geometrically — APPROVED** [review]

**Pull request merged**
