### PR TITLE
Issues Forms

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
# Forms :
image

image

# Results :
image

image

### CODE REVIEW

**Comment by Mysterious-Dev** [comment]
I hesitate to set some input to required or not.

**Review by Redblueflame — CHANGES_REQUESTED** [review]
No need to prefix everything if labels are already set in place.

**Comment by Mysterious-Dev** [comment]
It's fix

**Review by Redblueflame — APPROVED** [review]
Looks good to me. @Geometrically could you take a look at this?

**Pull request merged**
