### PR TITLE
fix(project): update follower count client side

### PR DESCRIPTION
**Pull request by MagnusHJensen**
**Description:**
Ensures the project followers on the client side is in-sync with the actions taken.

**Media:**

https://user-images.githubusercontent.com/32039051/224480515-ef39e6ba-55ac-455f-885e-56efd42607cd.mov

Closes: #437

### CODE REVIEW

**Review by triphora — COMMENTED** [review]
Wouldn't it be easier to add it to user(un)followProject in composables/user.js?

**Comment by MagnusHJensen** [comment]
Maybe, I just Saw the composables files as they should only have Logic relater to the name/file so user in this case, where incrementing and decrementing is not user related but more page specific in My mind.
I can easily change it if I misunderstood how they are separated :D

**Comment by triphora** [comment]
tbh, I don't know how it's "supposed to be" separated. In any event, incrementing and decrementing is going to be wanted no matter which page it's on.

**Comment by MagnusHJensen** [comment]
Moved to user composable

**Review by triphora — APPROVED** [review]

**Pull request merged**
