### PR TITLE
Simplify importing components and icons

### PR DESCRIPTION
**Pull request by venashial**
1. Switches component imports to be automatic through [@nuxt/components](https://github.com/nuxt/components). This means components don't have to be imported from their file and listed in the `components` property of a vue component.

2. Icons now use [lucide-vue](https://www.npmjs.com/package/lucide-vue), and the icon folders are deleted. The package supports tree-shaking. Icons now are more reliable and easy to use without manual imports.

P.S. I did shift around a few Babel related packages, so Nuxt uses `@nuxt/babel-preset-app`.

### CODE REVIEW

**Comment by venashial** [comment]
Deploy: https://knossos-venashial-git-nuxt-components-venashial.vercel.app/mods?q=

**Comment by venashial** [comment]
This PR is finished, but requires lucide-icons/lucide#390 to be accepted and released in the `lucide-vue` package.

**Comment by venashial** [comment]
This PR is even with [`apiv2-support`](https://github.com/modrinth/knossos/tree/apiv2-support) and complete.

**Comment by wafflecoffee** [comment]
@venashial Could you reopen this PR for the master branch? 'Twas GitHub silliness that closed it

**Comment by venashial** [comment]
This PR became increasing harder to keep even with each commit of changes. I don't fancy merging it with the main branch, but someone else might.

**Pull request closed without merging**
